# Generated by Django 3.2 on 2022-04-01 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20220331_2338'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuotations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('file', models.FileField(upload_to='supplier/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=255)),
                ('notify_on_station_upload', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SupplierQuotation',
                'verbose_name_plural': 'Supplier Quotations',
                'db_table': 'supplier_quotation',
            },
        ),
        migrations.CreateModel(
            name='StationQuotations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('file', models.FileField(upload_to='station/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplieraccount')),
            ],
            options={
                'verbose_name': 'StationQuotation',
                'verbose_name_plural': 'Station Quotations',
                'db_table': 'station_quotation',
            },
        ),
    ]
