# Generated by Django 3.2 on 2022-04-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
        ('core', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationquotations',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.servicestation'),
        ),
    ]
