# Generated by Django 3.2 on 2022-04-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20220331_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierEmployee',
        ),
    ]
